package handler

import (
	"order-manager/utils"
	"os"
	"path/filepath"

	"github.com/gofiber/fiber/v2"
)

func ExportAdvanceRequest(c *fiber.Ctx) error {
	// Generate a unique temporary filename
	filename := "Giấy đề xuất tạm ứng.pdf"
	err := utils.ExportAdvanceRequest(filename)
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error": "Failed to generate PDF file",
		})
	}
	// Get the temporary file path generated by utils
	tempFile := filepath.Join(os.TempDir(), filename)
	defer os.Remove(tempFile) // Clean up the temporary file
	return c.Download(tempFile, filename)
}
